### ISSUE TITLE
[Suggestion]Please make points on legal pages translatable

### ISSUE THREAD

**Issue by Blueberryy** [WeblateOrg/wllegal#1000]
### Describe the problem

Currently it is not possible to translate `a)`, `b)`, `c)`, `d)`, `e)`, `f)`, `g)`, `h)`, `i)`, `j)`, `k)`, `l)`, `m)`, `n)`, and `o)`.
![image](https://github.com/user-attachments/assets/db8713cf-5cd3-422e-aff7-a75cc46a13f9)

### Describe the solution you would like

Please add them to Hosted: Legal project!

**Comment by nijel** [comment]
It is here: https://hosted.weblate.org/translate/weblate/legal/en/?checksum=24fdcce4cb7d5828. Or you mean the points? Those are generated by CSS, what would you use instead of the letters there?

**Comment by Blueberryy** [comment]
> It is here: https://hosted.weblate.org/translate/weblate/legal/en/?checksum=24fdcce4cb7d5828. Or you mean the points? Those are generated by CSS, what would you use instead of the letters there?

Well, i would use Russian alphabetical letters there, if possible.

**Comment by Blueberryy** [comment]
Also, another suggestion: please make this link editable to i can replace `en` to `ru` and it will automatically lead to Russian version of page.
![image](https://github.com/user-attachments/assets/2431a05e-0354-4bb8-95e8-f42ed6b40163)
