### ISSUE TITLE
New privacy policy/CLA explanation

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/wllegal#562]
### Describe the problem

Is anything new processed? (That seems to be the only change of language.)

### Describe the solution you'd like

Could be explained in detail, what happens to any given data, with all relevant parties mentioned.

**Comment by orangesunny** [comment]
As @nijel says, this is to clarify the event when you purchase a service from Weblate. As we are not a financial institution, we work with our banks (and card-payment gateway provider if you pay by card) to process the purchase. The only customer data passed from us to the payment provider is currently e-mail in case of card payment.

Weblate never sold, does not, and will never sell any data.

We discussed the new version of the terms with privacy-focused people from FOSS communities like MetaBrainz and EFF. The scope was to make it more specific and less broad. To cut out unessential parts and provide better-descriptive Overview points. Changes’ description is on https://github.com/WeblateOrg/wllegal/pull/551.
